llm:
  google:
    model_name: gemini-2.0-flash
    base_url: https://api.google.com/v1
  openai:
    model_name: gpt-4o-mini
    base_url: https://api.openai.com/v1
  anthropic:
    model_name: claude-3-5-sonnet-20240620
    base_url: https://api.anthropic.com/v1